config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "cooks#index"
  resources :cooks do
  resources :reviews, only: :create
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cook.rb
class Cook < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :country
  belongs_to :serving

  has_one_attached :image
  has_many :reviews
  belongs_to :user

  with_options presence: true do
    validates :cook_name
    validates :recipe
    validates :material
    validates :country_id
    validates :serving_id
    validates :image
  end

  with_options numericality: { other_than: 1 , message: "can't be blank"} do
    validates :country_id
    validates :serving_id
  end
end

app/models/country.rb
class Country < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '日本🇯🇵' },
    { id: 3, name: '2~3日で発送' },
    { id: 4, name: '4~7日で発送' }
  ]

  include ActiveHash::Associations
  has_many :cooks
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :cook
  validates :rate, numericality: {
    less_than_or_equal_to: 5,
    greater_than_or_equal_to: 1}, presence: true
end

app/models/serving.rb
class Serving < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '一人前' },
    { id: 3, name: '二人前' },
    { id: 4, name: '4~7日で発送' }
  ]

  include ActiveHash::Associations
  has_many :cooks
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :cooks
         has_many :reviews
         validates :nickname, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/cooks_controller.rb
class CooksController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :destroy]
  before_action :set_cook, only: [:edit, :show, :update, :destroy]
  before_action :move_to_index, only: [:edit, :destroy]

  def index
    @cooks = Cook.includes(:user).order('created_at DESC')
  end

  def new
    @cook = Cook.new
  end

  def create
    @cook = Cook.new(cook_params)
    if @cook.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @review = Review.new
    @reviews = @cook.reviews.includes(:user)
  end

  def edit
  end

  def update
    if @cook.update(cook_params)
      redirect_to cook_path
    else
      render :edit
    end
  end

  def destroy
    redirect_to root_path if @cook.destroy
  end

  private

  def cook_params
    params.require(:cook).permit(:cook_name, :recipe, :material, :country_id, :serving_id, :image).merge(user_id: current_user.id)
  end

  def set_cook
    @cook = Cook.find(params[:id])
  end

  def move_to_index
    redirect_to action: :index if current_user.id != @cook.user_id
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @review = Review.new(review_params)
    if @review.save
      redirect_to cook_path(params[:cook_id])
    else
      @cook = @review.cook
      @reviews = @cook.reviews
      render "cooks/show"
    end
  end

  private
  def review_params
    params.require(:review).permit(:rate,:comment).merge(user_id: current_user.id,cook_id: params[:cook_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cooks_helper.rb
module CooksHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/cooks/edit.html.erb
<%# cssは商品出品のものを併用しています。
app/assets/stylesheets/items/new.css %>

<div class="items-sell-contents">
  <header class="items-sell-header">
    <%= link_to image_tag('furima-logo-color.png' , size: '185x50'), "/" %>
  </header>
  <div class="items-sell-main">
    <h2 class="items-sell-title">商品の情報を入力</h2>
    <%= form_with local: true do |f| %>

    <%# インスタンスを渡して、エラー発生時にメッセージが表示されるようにしましょう。%>
    <%# render 'shared/error_messages', model: f.object %>
    <%# //インスタンスを渡して、エラー発生時にメッセージが表示されるようにしましょう。%>

    <%# 商品画像 %>
    <div class="img-upload">
      <div class="weight-bold-text">
        商品画像
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :hoge, id:"item-image" %>
      </div>
    </div>
    <%# /商品画像 %>
    <%# 商品名と商品説明 %>
    <div class="new-items">
      <div class="weight-bold-text">
        商品名
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :hoge, class:"items-text", id:"item-name", placeholder:"商品名（必須 40文字まで)", maxlength:"40" %>
      <div class="items-explain">
        <div class="weight-bold-text">
          商品の説明
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :hoge, class:"items-text", id:"item-info", placeholder:"商品の説明（必須 1,000文字まで）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。" ,rows:"7" ,maxlength:"1000" %>
      </div>
    </div>
    <%# /商品名と商品説明 %>

    <%# 商品の詳細 %>
    <div class="items-detail">
      <div class="weight-bold-text">商品の詳細</div>
      <div class="form">
        <div class="weight-bold-text">
          カテゴリー
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:hoge, [], :hoge, :hoge, {}, {class:"select-box", id:"item-category"}) %>
        <div class="weight-bold-text">
          商品の状態
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:hoge, [], :hoge, :hoge, {}, {class:"select-box", id:"item-sales-status"}) %>
      </div>
    </div>
    <%# /商品の詳細 %>

    <%# 配送について %>
    <div class="items-detail">
      <div class="weight-bold-text question-text">
        <span>配送について</span>
        <a class="question" href="#">?</a>
      </div>
      <div class="form">
        <div class="weight-bold-text">
          配送料の負担
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:hoge, [], :hoge, :hoge, {}, {class:"select-box", id:"item-shipping-fee-status"}) %>
        <div class="weight-bold-text">
          発送元の地域
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:hoge, [], :hoge, :hoge, {}, {class:"select-box", id:"item-prefecture"}) %>
        <div class="weight-bold-text">
          発送までの日数
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:hoge, [], :hoge, :hoge, {}, {class:"select-box", id:"item-scheduled-delivery"}) %>
      </div>
    </div>
    <%# /配送について %>

    <%# 販売価格 %>
    <div class="sell-price">
      <div class="weight-bold-text question-text">
        <span>販売価格<br>(¥300〜9,999,999)</span>
        <a class="question" href="#">?</a>
      </div>
      <div>
        <div class="price-content">
          <div class="price-text">
            <span>価格</span>
            <span class="indispensable">必須</span>
          </div>
          <span class="sell-yen">¥</span>
          <%= f.text_field :hoge, class:"price-input", id:"item-price", placeholder:"例）300" %>
        </div>
        <div class="price-content">
          <span>販売手数料 (10%)</span>
          <span>
            <span id='add-tax-price'></span>円
          </span>
        </div>
        <div class="price-content">
          <span>販売利益</span>
          <span>
            <span id='profit'></span>円
          </span>
        </div>
      </div>
    </div>
    <%# /販売価格 %>

    <%# 注意書き %>
    <div class="caution">
      <p class="sentence">
        <a href="#">禁止されている出品、</a>
        <a href="#">行為</a>
        を必ずご確認ください。
      </p>
      <p class="sentence">
        またブランド品でシリアルナンバー等がある場合はご記載ください。
        <a href="#">偽ブランドの販売</a>
        は犯罪であり処罰される可能性があります。
      </p>
      <p class="sentence">
        また、出品をもちまして
        <a href="#">加盟店規約</a>
        に同意したことになります。
      </p>
    </div>
    <%# /注意書き %>
    <%# 下部ボタン %>
    <div class="sell-btn-contents">
      <%= f.submit "変更する" ,class:"sell-btn" %>
      <%=link_to 'もどる', "#", class:"back-btn" %>
    </div>
    <%# /下部ボタン %>
  </div>
  <% end %>

  <footer class="items-sell-footer">
    <ul class="menu">
      <li><a href="#">プライバシーポリシー</a></li>
      <li><a href="#">フリマ利用規約</a></li>
      <li><a href="#">特定商取引に関する表記</a></li>
    </ul>
    <%= link_to image_tag('furima-logo-color.png' , size: '185x50'), "/" %>
    <p class="inc">
      ©︎Furima,Inc.
    </p>
  </footer>
</div>

app/views/cooks/index.html.erb
<%= render "shared/header" %>
<div class='main'>

  <%# 画面上部の「人生を変えるフリマアプリ」帯部分 %>
  <div class='title-contents'>
    <h2 class='service-title'>
      人生を変えるフリマアプリ
    </h2>
    <p class='service-explain'>
      FURIMAはだれでもかんたんに出品・購入できる
    </p>
    <p class='service-explain'>
      フリマアプリです
    </p>
    <div class='store-btn'>
      <%= link_to image_tag("app-store.svg", class:"apple-btn"), "#" %>
      <%= link_to image_tag("google-play.png", class:"google-btn"), "#" %>
    </div>
  </div>
  <%# /画面上部の「人生を変えるフリマアプリ」帯部分  %>

  <%# FURIMAが選ばれる3つの理由部分 %>
  <div class='select-reason-contents'>
    <h2 class='title'>
      FURIMAが選ばれる3つの理由
    </h2>
    <ul class='reason-lists'>
      <li class='list'>
        <%= image_tag "furima-intro01.png", class:"list-pict" %>
        <span class='reason-list-number'>1</span>
        <h3 class='reason-list-text'>
          <span class='reason-list-blue-text'>3分</span>
          ですぐに出品
        </h3>
        <p class='reason-list-description'>
          スマホで入力するだけで簡単に出品できる！
        </p>
      </li>
      <li class='list'>
        <%= image_tag "furima-intro02.png", class:"list-pict" %>
        <span class='reason-list-number'>2</span>
        <h3 class='reason-list-text'>
          <span class='reason-list-blue-text'>シンプル</span>
          で使いやすい
        </h3>
        <p class='reason-list-description'>
          めんどくさい入力は必要なく、検索も購入もスムーズ！
        </p>
      </li>
      <li class='list'>
        <%= image_tag "furima-intro03.png", class:"list-pict" %>
        <span class='reason-list-number'>3</span>
        <h3 class='reason-list-text'>
          手数料
          <span class='reason-list-blue-text'>業界最安</span>
        </h3>
        <p class='reason-list-description'>
          10%でお得に出品&購入！
        </p>
      </li>
    </ul>
  </div>
  <%# /FURIMAが選ばれる3つの理由部分 %>

  <%# 画面中央の「会員数日本一位」帯部分 %>
  <div class='ad-contents'>
    <h2 class='ad-title'>
      会員数日本一位
    </h2>
    <p class='ad-explain'>
      FURIMAは、フリマアプリで最も人気。
    </p>
    <p class='ad-explain'>
      出品・購入回数も業界最多です！
    </p>
    <p class='ad-explain'>
      ほしかったあの商品に出会えるかもしれません。
    </p>
    <div class='store-btn'>
      <%= link_to image_tag("app-store.svg", class:"apple-btn"), "#" %>
      <%= link_to image_tag("google-play.png", class:"google-btn"), "#" %>
    </div>
  </div>
  <%# /画面中央の「会員数日本一位」帯部分 %>

  <%# FURIMAの特徴 %>
  <div class='feature-contents'>
    <h2 class='title'>
      FURIMAの特徴
    </h2>
    <ul class='feature-lists'>
      <li class='list'>
        <%= image_tag "furima-intro04.png", class:"list-pict" %>
        <h3 class='feature-list-text'>
          簡単に売り買いできる
        </h3>
        <p class='feature-list-description'>
          スマホひとつで、いつでもどこでも簡単に出品・購入が可能！
        </p>
      </li>
      <li class='list'>
        <%= image_tag "furima-intro05.png", class:"list-pict" %>
        <h3 class='feature-list-text'>
          売上金は即日振込みに対応
        </h3>
        <p class='feature-list-description'>
          午前9時までに振込を依頼いただければ、翌日に指定の口座に入金いたします。
        </p>
      </li>
      <li class='list'>
        <%= image_tag "furima-intro06.png", class:"list-pict" %>
        <h3 class='feature-list-text'>
          様々な支払いに対応
        </h3>
        <p class='feature-list-description'>
          お支払いは、クレジットカードだけでなく、ポイントや売上金など多彩な方法があります。
        </p>
      </li>
    </ul>
  </div>
  <%# /FURIMAの特徴 %>

  <%# 商品一覧 %>
  <div class='item-contents'>
    <h2 class='title'>ピックアップカテゴリー</h2>
    <div class="subtitle" >
      新規投稿商品
    </div>
    <ul class='item-lists'>
     <% if @cooks.present? %>
      <% @cooks.each do |cook| %>
      <li class='list'>
        <%= link_to cook_path(cook) do %>
        <div class='item-img-content'>
          <%= image_tag cook.image, class: "item-img" %>
          
          
        </div>
        <div class='item-info'>
          <h3 class='item-name'>
            <%= cook.cook_name %>
          </h3>
          <div class='item-price'>
            <span><%= cook.serving.name %>円<br><%= cook.serving.name %></span>
            <div class='star-btn'>
              <%= image_tag "star.png", class:"star-icon" %>
              <span class='star-count'>0</span>
            </div>
          </div>
        </div>
        <% end %>
      </li>
      <% end %>
      <% else %>
      <li class='list'>
        <%= link_to '#' do %>
        <%= image_tag "https://tech-master.s3.amazonaws.com/uploads/curriculums/images/Rails1-4/sample.jpg", class: "item-img" %>
        <div class='item-info'>
          <h3 class='item-name'>
            商品を出品してね！
          </h3>
          <div class='item-price'>
            <span>99999999円<br>(税込み)</span>
            <div class='star-btn'>
              <%= image_tag "star.png", class:"star-icon" %>
              <span class='star-count'>0</span>
            </div>
          </div>
        </div>
        <% end %>
      </li>
    </ul>
  </div>
  <% end %>
  <%# /商品一覧 %>
</div>
<%= link_to(new_cook_path, class: 'purchase-btn') do %>
  <span class='purchase-btn-text'>出品する</span>
  <%= image_tag 'icon_camera.png' , size: '185x50' ,class: "purchase-btn-icon" %>
<% end %>
<%= render "shared/footer" %>

app/views/cooks/new.html.erb
<div class="items-sell-contents">
  <header class="items-sell-header">
    <%= link_to image_tag('furima-logo-color.png' , size: '185x50'), "/" %>

  </header>
  <div class="items-sell-main">
    <h2 class="items-sell-title">料理の情報を入力</h2>
    <%= form_with model: @cook, local: true do |f| %>

    <%# インスタンスを渡して、エラー発生時にメッセージが表示されるようにしましょう。%>
    <%# render 'shared/error_messages', model: f.object %>
    <%# //インスタンスを渡して、エラー発生時にメッセージが表示されるようにしましょう。%>

    <%# 商品画像 %>
    <div class="img-upload">
      <div class="weight-bold-text">
        料理画像🍳
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"item-image" %>
      </div>
    </div>
    <%# /商品画像 %>
    <%# 商品名と商品説明 %>
    <div class="items-detail">
      <div class="weight-bold-text">料理の詳細</div>
      <div class="form">
        <div class="weight-bold-text">
          国名🌍
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:country_id, Country.all, :id, :name , {}, {class:"select-box", id:"item-category"}) %>
        <div class="weight-bold-text">
          何人分
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:serving_id, Serving.all, :id, :name , {}, {class:"select-box", id:"item-sales-status"}) %>
      </div>
    </div>
    <div class="new-items">
      <div class="weight-bold-text">
        料理名
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :cook_name, class:"items-text", id:"item-name", placeholder:"商品名（必須 40文字まで)", maxlength:"40" %>
      <div class="items-explain">
        <div class="weight-bold-text">
          材料
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :material, class:"items-text", id:"item-info", placeholder:"商品の説明（必須 1,000文字まで）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。" ,rows:"7" ,maxlength:"1000" %>
      </div>
      <div class="items-explain">
        <div class="weight-bold-text">
          レシピ
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :recipe, class:"items-text", id:"item-info", placeholder:"商品の説明（必須 1,000文字まで）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。" ,rows:"7" ,maxlength:"1000" %>
      </div>
    </div>
    <%# /商品名と商品説明 %>

    <%# 商品の詳細 %>
    
    
    <div class="caution">
      <p class="sentence">
        <a href="#">禁止されている出品、</a>
        <a href="#">行為</a>
        を必ずご確認ください。
      </p>
      <p class="sentence">
        またブランド品でシリアルナンバー等がある場合はご記載ください。
        <a href="#">偽ブランドの販売</a>
        は犯罪であり処罰される可能性があります。
      </p>
      <p class="sentence">
        また、出品をもちまして
        <a href="#">加盟店規約</a>
        に同意したことになります。
      </p>
    </div>
    <%# /注意書き %>
    <%# 下部ボタン %>
    <div class="sell-btn-contents">
      <%= f.submit "出品する" ,class:"sell-btn" %>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
    <%# /下部ボタン %>
  </div>
  <% end %>

  <footer class="items-sell-footer">
    <ul class="menu">
      <li><a href="#">プライバシーポリシー</a></li>
      <li><a href="#">フリマ利用規約</a></li>
      <li><a href="#">特定商取引に関する表記</a></li>
    </ul>
    <%= link_to image_tag('furima-logo-color.png' , size: '185x50'), "/" %>
    <p class="inc">
      ©︎Furima,Inc.
    </p>
  </footer>
</div>

app/views/cooks/show.html.erb
<%= render "shared/header" %>

<%# 商品の概要 %>
<div class="item-show">
  <div class="item-box">
    <h2 class="name">
      <%= @cook.cook_name %>
    </h2>
    <div class="item-img-content">
      <%= image_tag @cook.image ,class:"item-box-img" %>
      <%# 商品が売れている場合は、sold outを表示しましょう %>
      
      <%# //商品が売れている場合は、sold outを表示しましょう %>
    </div>
    

    <%# ログインしているユーザーと出品しているユーザーが、同一人物の場合と同一人物ではない場合で、処理を分けましょう %>

    <%= link_to "商品の編集", edit_cook_path, method: :get, class: "item-red-btn" %>
    <p class="or-text">or</p>
    <%= link_to "削除", cook_path, method: :delete, class:"item-destroy" %>

    <%# 商品が売れていない場合はこちらを表示しましょう %>
    
    <%# //商品が売れていない場合はこちらを表示しましょう %>


    <%# //ログインしているユーザーと出品しているユーザーが、同一人物の場合と同一人物ではない場合で、処理を分けましょう %>

    <div class="item-explain-box">
      <span><%= "商品説明" %></span>
    </div>
    <table class="detail-table">
      <tbody>
        <tr>
          <th class="detail-item">出品者</th>
          <td class="detail-value"><%= @cook.user.nickname %></td>
        </tr>
        <tr>
          <th class="detail-item">カテゴリー</th>
          <td class="detail-value"><%= @cook.country.name %></td>
        </tr>
        <tr>
          <th class="detail-item">商品の状態</th>
          <td class="detail-value"><%= @cook.serving.name %></td>
        </tr>
        <tr>
          <th class="detail-item">配送料の負担</th>
          <td class="detail-value"><%= @cook.material %></td>
        </tr>
        <tr>
          <th class="detail-item">発送元の地域</th>
          <td class="detail-value"><%= @cook.recipe %></td>
        </tr>
        
      </tbody>
    </table>
    <div class="option">
      <div class="favorite-btn">
        <%= image_tag "star.png" ,class:"favorite-star-icon" ,width:"20",height:"20"%>
        <span>お気に入り 0</span>
      </div>
      <div class="report-btn">
        <%= image_tag "flag.png" ,class:"report-flag-icon" ,width:"20",height:"20"%>
        <span>不適切な商品の通報</span>
      </div>
    </div>
  </div>
  <%# /商品の概要 %>

<%= form_with model: [@cook, @review], local: true do |f| %>
    <%# render 'layouts/error_messages', object: f.object %>

    <%= f.text_area :comment, rows:'5', placeholder: "商品のコメント", class: "form-control form-control-sm" %>
    <div id="rating-form">
        <label>評価：</label>
        <%# scoreNameの値をhidden_fieldでカラムに送っている %>
        <%= f.hidden_field :rate, :value => 'score' %>
    </div>

    <%= f.submit "投稿する" %>
<% end %>


<script>
    $('#rating-form').raty({
        starOn: "<%= asset_path('star-on.png') %>",
        starOff: "<%= asset_path('star-off.png') %>",
        scoreName: 'review[rate]'
    });
</script>
  <div class="links">
    <a href="#" class="change-item-btn">
      ＜ 前の商品
    </a>
    <a href="#" class="change-item-btn">
      後ろの商品 ＞
    </a>
  </div>
  <%# 詳細ページで表示されている商品のカテゴリー名を表示しましょう %>
  <a href="#" class="another-item"><%= "商品のカテゴリー名" %>をもっと見る</a>
  <%# //詳細ページで表示されている商品のカテゴリー名を表示しましょう %>
</div>

<%= render "shared/footer" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>WorldCook</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <script type="text/javascript" src="https://js.pay.jp/v1/"></script>
  <%= stylesheet_link_tag 'application', media: 'all'%>
  <%= javascript_pack_tag 'application' %>
</head>

<body>
  <%= yield %>
</body>

</html>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<%# 下部広告部分 %>
<div class='ad-footer-contents'>
  <p class='ad-footer-explain'>
    だれでもかんたん、人生を変えるフリマアプリ
  </p>
  <h2 class='ad-footer-title'>
    今すぐ無料ダウンロード！
  </h2>
  <div class='store-btn'>
    <%= link_to image_tag("app-store.svg", class:"apple-btn"), "#" %>
    <%= link_to image_tag("google-play.png", class:"google-btn"), "#" %>
  </div>
</div>
<%# /下部広告部分 %>

<div class='footer'>
  <div class='footer-contents'>
    <div class='furima-details'>
      <h2 class='footer-content-head'>WorldCookについて</h2>
      <ul>
        <li><%= link_to '会社概要（運営会社)', "#", class: "footer-link" %></li>
        <li><%= link_to 'プライバシーポリシー', "#", class: "footer-link" %></li>
        <li><%= link_to 'WorldCook利用規約', "#", class: "footer-link" %></li>
        <li><%= link_to 'ポイントに関する特約', "#", class: "footer-link" %></li>
      </ul>
    </div>
    <div class='furima-details'>
      <h2 class='footer-content-head'>WorldCookを見る</h2>
      <ul>
        <li><%= link_to 'カテゴリー一覧', "#", class: "footer-link" %></li>
        <li><%= link_to 'ブランド一覧', "#", class: "footer-link" %></li>
      </ul>
    </div>
    <div class='furima-details'>
      <h2 class='footer-content-head'>FURIMAについて</h2>
      <ul>
        <li><%= link_to 'WorldCookガイド', "#", class: "footer-link" %></li>
        <li><%= link_to 'WorldCookロゴ利用ガイドライン', "#", class: "footer-link" %></li>
        <li><%= link_to 'お知らせ', "#", class: "footer-link" %></li>
      </ul>
    </div>
  </div>
  <%= link_to image_tag("furima-logo-white.png", class:"logo-white"), "#" %>
  <p>© WorldCook</p>
</div>

app/views/shared/_form.html.erb
<%= form_with model: [@cook, @review], local: true do |f| %>
    <%# render 'layouts/error_messages', object: f.object %>

    <%= f.text_area :comment, rows:'5', placeholder: "商品のコメント", class: "form-control form-control-sm" %>
    <div id="rating-form">
        <label>評価：</label>
        <%# scoreNameの値をhidden_fieldでカラムに送っている %>
        <%= f.hidden_field :rate, :value => 'score' %>
    </div>

    <%= f.submit "投稿する" %>
<% end %>


<script>
    $('#rating-form').raty({
        starOn: "<%= asset_path('star-on.png') %>",
        starOff: "<%= asset_path('star-off.png') %>",
        scoreName: 'review[rate]'
    });
</script>

app/views/shared/_header.html.erb
<%# CSS・・・assets/stylesheets/shared/header.css %>
<header class='top-page-header'>
  <div class='search-bar-contents'>
    <%= link_to image_tag("ar.jpeg", class:"furima-icon"), "/" %>
    <form class="search-form" action="#">
      <input class='input-box' placeholder='キーワードから探す'>
      <button class="search-button">
        <%= image_tag "search.png", class:"search-icon" %>
      </button>
    </form>
  </div>
  <div class='nav'>
    <ul class='lists-left'>
      <li><%= link_to 'カテゴリー', "#", class: "category-list" %></li>
      <li><%= link_to 'ブランド', "#", class: "brand-list" %></li>
    </ul>
    <ul class='lists-right'>
      <%# deviseを導入できたら、ログインの有無で表示が変わるように分岐しましょう%>
      <% if user_signed_in? %>
      <li><%= link_to current_user.nickname, "#", class: "user-nickname" %></li>
      <li><%= link_to 'ログアウト', destroy_user_session_path , method: :delete, class: "logout" %></li>
      <% else %>
      <li><%= link_to 'ログイン', new_user_session_path , class: "login" %></li>
      <li><%= link_to '新規登録', new_user_registration_path , class: "sign-up" %></li>
      <% end %>
      <%# //deviseを導入できたら、ログインの有無で表示が変わるように分岐しましょう%>
    </ul>
  </div>
</header>

app/views/shared/_second-footer.html.erb
<footer class='second-fotter'>
  <div class='second-fotter-text-wrap'>
    <p class='second-fotter-text'>プライバシーポリシー</p>
    <p class='second-fotter-text'>WorldCook利用規約</p>
    <p class='second-fotter-text'>特定商取引に関する表記</p>
  </div>
  <%= image_tag "furima-logo-color.png", class:"second-fotter-logo"%>
</footer>

app/views/shared/_second-header.html.erb
<header class='second-header'>
  <%= link_to image_tag("furima-logo-color.png", class:"second-logo"), "/" %>
</header>